/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { 
  DeviceConfig, 
  StudioTab, 
  DeviceType, 
  ViewAngle 
} from './types/index.ts';
import { DEFAULT_README_MARKDOWN } from './data/readmeContent.ts';
import { Header } from './components/Header.tsx';
import { MockupViewer } from './components/MockupViewer.tsx';
import { DeviceControls } from './components/DeviceControls.tsx';
import { ReadmeViewer } from './components/ReadmeViewer.tsx';
import { ReadmeEditor } from './components/ReadmeEditor.tsx';
import { BadgeGenerator } from './components/BadgeGenerator.tsx';
import { MockupBanners } from './components/MockupBanners.tsx';
import { 
  Laptop, 
  FileText, 
  Check, 
  Copy, 
  Sparkles, 
  Download, 
  ArrowRight,
  ShieldCheck,
  Terminal,
  ExternalLink
} from 'lucide-react';

export default function App() {
  const [activeTab, setActiveTab] = useState<StudioTab>('mockup-studio');
  const [markdown, setMarkdown] = useState<string>(DEFAULT_README_MARKDOWN);
  const [isEditingMarkdown, setIsEditingMarkdown] = useState<boolean>(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const [deviceConfig, setDeviceConfig] = useState<DeviceConfig>({
    device: 'macbook',
    color: 'space-black',
    angle: 'hero',
    backdrop: 'midnight-glow',
    reflection: true,
    shadowIntensity: 75,
    zoom: 95,
    contentType: 'live-dashboard',
    is3dInteractive: true,
  });

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3200);
  };

  const handleConfigChange = (updated: Partial<DeviceConfig>) => {
    setDeviceConfig(prev => ({ ...prev, ...updated }));
  };

  const handleApplyPreset = (preset: 'hero' | 'minimal' | 'mobile' | 'studio') => {
    switch (preset) {
      case 'hero':
        setDeviceConfig({
          ...deviceConfig,
          device: 'macbook',
          angle: 'hero',
          backdrop: 'midnight-glow',
          color: 'space-black',
          reflection: true,
          zoom: 95,
        });
        showToast('Applied "Hero Perspective" preset');
        break;
      case 'minimal':
        setDeviceConfig({
          ...deviceConfig,
          device: 'browser',
          angle: 'flat',
          backdrop: 'studio-slate',
          color: 'silver',
          reflection: false,
          zoom: 100,
        });
        showToast('Applied "Docs Clean Flat" preset');
        break;
      case 'mobile':
        setDeviceConfig({
          ...deviceConfig,
          device: 'iphone',
          angle: 'flat',
          backdrop: 'cyber-neon',
          color: 'space-black',
          reflection: true,
          zoom: 100,
        });
        showToast('Applied "iPhone 16 Pro Focus" preset');
        break;
      case 'studio':
        setDeviceConfig({
          ...deviceConfig,
          device: 'studio-display',
          angle: 'flat',
          backdrop: 'desk-wood',
          color: 'silver',
          reflection: true,
          zoom: 90,
        });
        showToast('Applied "Apple Studio Display 32" preset');
        break;
    }
  };

  const handleDownloadReadme = () => {
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'README.md';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showToast('Downloaded README.md successfully!');
  };

  const handleExportMarkdownSnippet = () => {
    const snippet = `<!-- Pro Mockup Generated by README Pro Studio -->
<div align="center">
  <img src="https://readmepro.studio/api/mockup?device=${deviceConfig.device}&angle=${deviceConfig.angle}&color=${deviceConfig.color}" alt="${deviceConfig.device} Pro Mockup" width="100%"/>
</div>`;
    navigator.clipboard.writeText(snippet);
    showToast('Copied Mockup Markdown embed tag to clipboard!');
  };

  const handleDownloadMockupImage = () => {
    // Generate high quality canvas rendering for download
    const svgData = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 750" width="1200" height="750">
      <defs>
        <radialGradient id="bg" cx="50%" cy="40%" r="65%">
          <stop offset="0%" stop-color="#1e1b4b"/>
          <stop offset="60%" stop-color="#0b0c14"/>
          <stop offset="100%" stop-color="#030712"/>
        </radialGradient>
        <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
          <feDropShadow dx="0" dy="25" stdDeviation="35" flood-color="#000" flood-opacity="0.8"/>
        </filter>
      </defs>
      <rect width="100%" height="100%" fill="url(#bg)"/>
      <g filter="url(#shadow)" transform="translate(150, 80)">
        <rect width="900" height="560" rx="20" fill="#18181b" stroke="#3f3f46" stroke-width="2"/>
        <rect x="25" y="25" width="850" height="510" rx="12" fill="#09090b"/>
        <!-- Notch -->
        <rect x="375" y="25" width="150" height="24" rx="10" fill="#000000"/>
        <circle cx="450" cy="37" r="4" fill="#18181b"/>
        <circle cx="470" cy="37" r="2" fill="#22c55e"/>
        <!-- Inner Dashboard UI mock -->
        <rect x="25" y="49" width="850" height="40" fill="#18181b"/>
        <circle cx="55" cy="69" r="6" fill="#3b82f6"/>
        <text x="75" y="74" fill="#ffffff" font-family="system-ui, sans-serif" font-weight="700" font-size="14">VertexCloud Telemetry</text>
        <rect x="50" y="110" width="180" height="90" rx="8" fill="#18181b" stroke="#27272a"/>
        <text x="65" y="140" fill="#94a3b8" font-family="system-ui, sans-serif" font-size="11">Throughput</text>
        <text x="65" y="175" fill="#ffffff" font-family="system-ui, sans-serif" font-weight="800" font-size="20">2.48M req/s</text>
        <rect x="250" y="110" width="180" height="90" rx="8" fill="#18181b" stroke="#27272a"/>
        <text x="265" y="140" fill="#94a3b8" font-family="system-ui, sans-serif" font-size="11">P99 Latency</text>
        <text x="265" y="175" fill="#22c55e" font-family="system-ui, sans-serif" font-weight="800" font-size="20">24ms (Optimal)</text>
        <rect x="450" y="110" width="180" height="90" rx="8" fill="#18181b" stroke="#27272a"/>
        <text x="465" y="140" fill="#94a3b8" font-family="system-ui, sans-serif" font-size="11">Uptime (30d)</text>
        <text x="465" y="175" fill="#38bdf8" font-family="system-ui, sans-serif" font-weight="800" font-size="20">99.992%</text>
        <rect x="650" y="110" width="180" height="90" rx="8" fill="#18181b" stroke="#27272a"/>
        <text x="665" y="140" fill="#94a3b8" font-family="system-ui, sans-serif" font-size="11">Active Pods</text>
        <text x="665" y="175" fill="#a855f7" font-family="system-ui, sans-serif" font-weight="800" font-size="20">48 / 48</text>
        <!-- Graph placeholder -->
        <rect x="50" y="225" width="780" height="160" rx="8" fill="#18181b" stroke="#27272a"/>
        <path d="M 70 340 Q 180 260 290 300 T 510 250 T 730 280 L 800 240" fill="none" stroke="#3b82f6" stroke-width="4"/>
      </g>
      <!-- Base of laptop -->
      <path d="M 80 640 L 1120 640 L 1090 660 L 110 660 Z" fill="#27272a"/>
      <rect x="550" y="640" width="100" height="6" rx="3" fill="#09090b"/>
    </svg>`;

    const blob = new Blob([svgData], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pro-mockup-${deviceConfig.device}.svg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast(`Exported ${deviceConfig.device} mockup image!`);
  };

  return (
    <div className="min-h-screen bg-[#07080b] text-zinc-100 flex flex-col font-sans selection:bg-blue-600 selection:text-white">
      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed bottom-6 right-6 z-50 bg-zinc-900 border border-zinc-700 text-zinc-100 px-4 py-2.5 rounded-xl shadow-2xl flex items-center space-x-2 text-xs font-semibold animate-in fade-in slide-in-from-bottom-3 duration-200">
          <Check className="w-4 h-4 text-emerald-400" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Main Studio Navigation Header */}
      <Header
        activeTab={activeTab}
        onTabChange={(tab) => {
          setActiveTab(tab);
          if (tab === 'readme-viewer') {
            setIsEditingMarkdown(false);
          }
        }}
        onDownloadReadme={handleDownloadReadme}
        onCopyReadme={() => {
          navigator.clipboard.writeText(markdown);
          showToast('Copied full README.md content to clipboard!');
        }}
      />

      {/* Workspace Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8 space-y-6">

        {/* ========================================================= */}
        {/* VIEW 1: PRO MOCKUP STUDIO                                 */}
        {/* ========================================================= */}
        {activeTab === 'mockup-studio' && (
          <div className="space-y-6">
            {/* Top Info Banner */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-2 border-b border-zinc-800 gap-3">
              <div>
                <h1 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight flex items-center space-x-2">
                  <span>Pro Hardware Mockup Studio</span>
                  <span className="text-xs font-mono font-medium px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                    60 FPS Vector 3D
                  </span>
                </h1>
                <p className="text-xs text-zinc-400 mt-0.5">
                  Ultra-crisp 3D device frames with real clickable dashboard telemetry and publication-ready export.
                </p>
              </div>

              <div className="flex items-center space-x-2">
                <button
                  onClick={() => setActiveTab('readme-viewer')}
                  className="px-3.5 py-1.5 rounded-xl bg-zinc-900 hover:bg-zinc-800 text-xs font-medium text-zinc-200 border border-zinc-800 flex items-center space-x-1.5 transition active:scale-95"
                >
                  <FileText className="w-3.5 h-3.5 text-blue-400" />
                  <span>View in README.md</span>
                </button>
              </div>
            </div>

            {/* Mockup Canvas */}
            <MockupViewer
              config={deviceConfig}
              onConfigChange={handleConfigChange}
              onExportMarkdown={handleExportMarkdownSnippet}
              onDownloadImage={handleDownloadMockupImage}
            />

            {/* Studio Controls Panel */}
            <DeviceControls
              config={deviceConfig}
              onChange={handleConfigChange}
              onApplyPreset={handleApplyPreset}
            />
          </div>
        )}

        {/* ========================================================= */}
        {/* VIEW 2: README.MD VIEWER                                  */}
        {/* ========================================================= */}
        {activeTab === 'readme-viewer' && (
          <div>
            {isEditingMarkdown ? (
              <ReadmeEditor
                value={markdown}
                onChange={setMarkdown}
                onReset={() => {
                  setMarkdown(DEFAULT_README_MARKDOWN);
                  showToast('Reset README to default template');
                }}
                onDownload={handleDownloadReadme}
              />
            ) : (
              <ReadmeViewer
                markdownContent={markdown}
                onEditClick={() => setIsEditingMarkdown(true)}
                onOpenMockupClick={() => setActiveTab('mockup-studio')}
                onDownloadReadme={handleDownloadReadme}
              />
            )}
          </div>
        )}

        {/* ========================================================= */}
        {/* VIEW 3: SPLIT STUDIO (README on Left + Mockup on Right)   */}
        {/* ========================================================= */}
        {activeTab === 'split-view' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between pb-2 border-b border-zinc-800">
              <div>
                <h2 className="text-lg font-bold text-white">Split Studio: Live Documentation &amp; Device Mockup</h2>
                <p className="text-xs text-zinc-400">Synchronized view of the repository README alongside the real-time 3D device frame.</p>
              </div>
              <div className="flex items-center space-x-2">
                <button
                  onClick={handleExportMarkdownSnippet}
                  className="px-3 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-xs font-semibold text-white shadow"
                >
                  Copy Mockup Code
                </button>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start">
              {/* Left Column: Rendered README */}
              <div className="max-h-[750px] overflow-y-auto no-scrollbar rounded-2xl">
                <ReadmeViewer
                  markdownContent={markdown}
                  onEditClick={() => setIsEditingMarkdown(true)}
                  onOpenMockupClick={() => {}}
                  onDownloadReadme={handleDownloadReadme}
                />
              </div>

              {/* Right Column: Live Mockup with Sticky Controls */}
              <div className="space-y-4 sticky top-20">
                <MockupViewer
                  config={deviceConfig}
                  onConfigChange={handleConfigChange}
                  onExportMarkdown={handleExportMarkdownSnippet}
                  onDownloadImage={handleDownloadMockupImage}
                />
                <DeviceControls
                  config={deviceConfig}
                  onChange={handleConfigChange}
                  onApplyPreset={handleApplyPreset}
                />
              </div>
            </div>
          </div>
        )}

        {/* ========================================================= */}
        {/* VIEW 4: BADGE GENERATOR                                   */}
        {/* ========================================================= */}
        {activeTab === 'badge-creator' && (
          <BadgeGenerator />
        )}

        {/* ========================================================= */}
        {/* VIEW 5: HERO BANNER GENERATOR                             */}
        {/* ========================================================= */}
        {activeTab === 'banner-generator' && (
          <MockupBanners />
        )}

      </main>

      {/* Global Footer */}
      <footer className="w-full border-t border-zinc-900 bg-zinc-950/70 py-6 text-center text-xs text-zinc-500 mt-12">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center space-x-2">
            <span className="font-semibold text-zinc-300">README Pro &amp; Mockup Studio</span>
            <span>·</span>
            <span>Apache-2.0 License</span>
          </div>
          <div className="text-zinc-500 text-[11px]">
            Designed for engineers, indie hackers &amp; open-source maintainers.
          </div>
        </div>
      </footer>
    </div>
  );
}
